Add --system argument
Mic92/nixpkgs-review pull request #164
Opened 2021-01-24 21:22 UTC by B4dM4n

Add a `--system` argument, which can be used to evaluate and build packages for systems other than the local one.

It passes down the specified system to nix invocations when evaluating the package set as the `system` option. During evaluation it should not matter if the local nix can actually build packages for the system, as it primarily sets `builtins.currentSystem`. I'm not sure if this is also true for IFD evaluations.

When constructing the nix-shell with the packages to build, it sets the `nixpkgs { system = ...; }` config. This avoids miss-configuring the build environment with a system that can't actually be build locally and allows to use all the configured nix build systems.

2021-01-24 21:48 UTC, Mic92 commented
Would running a nix-shell actually makes sense if `currentSystem != system`?

2021-01-24 23:04 UTC, B4dM4n commented
Running a nix-shell also makes sense for systems which binaries can't be executed on the current machine. It still allows to inspect the folder structure of build products in `$buildInputs`.

Executing binaries only works when the given system is either the current system or in the `extra-platforms` list.

2021-01-24 23:40 UTC, Mic92 commented
> Running a nix-shell also makes sense for systems which binaries can't be executed on the current machine. It still allows to inspect the folder structure of build products in `$buildInputs`.
> 
> Executing binaries only works when the given system is either the current system or in the `extra-platforms` list.

Ok, so I guess there are also some errors because support hooks fail to execute?

2021-01-26 21:10 UTC, B4dM4n commented
> Ok, so I guess there are also some errors because support hooks fail to execute?

When a shell hook actually tries to execute native binaries on a non supported system, this obviously fails. If this failure ist not handled and propagated up to the shell environment, the shell exits with an error.

But looking at some setup hooks in nixpkgs, most of them only run shell code in the nix-shell environment and modify some variables. The stdenv of the nix-shell is actually from the local system, because the system is only changed for the imported nixpkgs. So most hooks will probably load fine.

For example, this hook will cause the nix-shell to exit, because it fails to execute at activation time:

```nix
myhellohook = makeSetupHook { } (writeShellScript "hellohook" "${hello}/bin/hello");
```

<details>
  <summary>nixpkgs-review wip --system x86_64-darwin</summary>

```
$ git -c fetch.prune=false fetch --force https://github.com/NixOS/nixpkgs master:refs/nixpkgs-review/0
$ git worktree add /home/fabian/.cache/nixpkgs-review/rev-c46b679be03303111d3b14d4e65495766c6b01e9-dirty-4/nixpkgs c46b679be03303111d3b14d4e65495766c6b01e9
Preparing worktree (detached HEAD c46b679be03)
Updating files: 100% (24185/24185), done.
HEAD is now at c46b679be03 sudo: 1.9.5p1 → 1.9.5p2
$ nix-env --option system x86_64-darwin -f /home/fabian/.cache/nixpkgs-review/rev-c46b679be03303111d3b14d4e65495766c6b01e9-dirty-4/nixpkgs -qaP --xml --out-path --show-trace
Applying `nixpkgs` diff...
$ nix-env --option system x86_64-darwin -f /home/fabian/.cache/nixpkgs-review/rev-c46b679be03303111d3b14d4e65495766c6b01e9-dirty-4/nixpkgs -qaP --xml --out-path --show-trace --meta
1 package added:
hook

$ nix --experimental-features nix-command build --no-link --keep-going --option build-use-sandbox relaxed -f /home/fabian/.cache/nixpkgs-review/rev-c46b679be03303111d3b14d4e65495766c6b01e9-dirty-4/build.nix
1 package built:
myhellohook

$ nix-shell /home/fabian/.cache/nixpkgs-review/rev-c46b679be03303111d3b14d4e65495766c6b01e9-dirty-4/shell.nix
bash: /nix/store/77ibvjda8qaj0fs14xmdiszva0zr8yja-hello-2.10/bin/hello: cannot execute binary file: Exec format error
$ git worktree prune
Traceback (most recent call last):
  File "/nix/store/5cch6aivya2j4hdmznrh8w47bhq0c4g0-nixpkgs-review-2.5.0/bin/.nixpkgs-review-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/5cch6aivya2j4hdmznrh8w47bhq0c4g0-nixpkgs-review-2.5.0/lib/python3.8/site-packages/nixpkgs_review/__init__.py", line 10, in main
    cli.main(command, args)
  File "/nix/store/5cch6aivya2j4hdmznrh8w47bhq0c4g0-nixpkgs-review-2.5.0/lib/python3.8/site-packages/nixpkgs_review/cli/__init__.py", line 247, in main
    args.func(args)
  File "/nix/store/5cch6aivya2j4hdmznrh8w47bhq0c4g0-nixpkgs-review-2.5.0/lib/python3.8/site-packages/nixpkgs_review/cli/wip.py", line 10, in wip_command
    review_local_revision(
  File "/nix/store/5cch6aivya2j4hdmznrh8w47bhq0c4g0-nixpkgs-review-2.5.0/lib/python3.8/site-packages/nixpkgs_review/review.py", line 458, in review_local_revision
    review.review_commit(builddir.path, args.branch, args.remote, commit, staged)
  File "/nix/store/5cch6aivya2j4hdmznrh8w47bhq0c4g0-nixpkgs-review-2.5.0/lib/python3.8/site-packages/nixpkgs_review/review.py", line 253, in review_commit
    self.start_review(self.build_commit(branch_rev, reviewed_commit, staged), path)
  File "/nix/store/5cch6aivya2j4hdmznrh8w47bhq0c4g0-nixpkgs-review-2.5.0/lib/python3.8/site-packages/nixpkgs_review/review.py", line 242, in start_review
    nix_shell(report.built_packages(), path, self.system)
  File "/nix/store/5cch6aivya2j4hdmznrh8w47bhq0c4g0-nixpkgs-review-2.5.0/lib/python3.8/site-packages/nixpkgs_review/nix.py", line 45, in nix_shell
    sh(["nix-shell", str(shell)], cwd=cache_directory)
  File "/nix/store/5cch6aivya2j4hdmznrh8w47bhq0c4g0-nixpkgs-review-2.5.0/lib/python3.8/site-packages/nixpkgs_review/utils.py", line 30, in sh
    return subprocess.run(command, cwd=cwd, check=True, text=True)
  File "/nix/store/2wwb85hrvvfzkhrlwcj3pqi60nlbi9cq-python3-3.8.7/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['nix-shell', '/home/fabian/.cache/nixpkgs-review/rev-c46b679be03303111d3b14d4e65495766c6b01e9-dirty-4/shell.nix']' returned non-zero exit status 126.
```
</details>

Instead of disabling the nix-shell on unsupported systems, we could add a warning about unintended side-effects when executing code for foreign systems.

2021-01-27 22:37 UTC, Mic92 commented
Ok. I will redo unit-tests to rely less on mocking.

2021-02-21 07:21 UTC, Mic92 commented
Sorry for the delay. I have rewritten the unittests now. Could you rebase?

2021-02-24 15:34 UTC, B4dM4n commented
Rebase is done.

I had issues building the package with the current `flake.lock`. The `nixpkgs` input is locked with `"type": "path"` which results in the following error when trying to build it:

```log
$ nix build
error (ignored): error: bad archive: input doesn't look like a Nix archive
error: getting status of '/nix/store/z87z2f1vf6wzjl9nh1rs7k1ki9s6yf2k-source': No such file or directory
(use '--show-trace' to show detailed location information)
```

Updating the input to my own pinned version fixed the problem, but probably used another revision.

2021-02-24 18:16 UTC, Mic92 commented on flake.lock
> -        "type": "path"
my bad.

2021-03-06 09:40 UTC, Mic92 commented
This does not quite work yet:

```console
% ~/git/nixpkgs-review/bin/nix-review pr --system=aarch64-linux 98734
$ git -c fetch.prune=false fetch --force https://github.com/NixOS/nixpkgs master:refs/nixpkgs-review/0 pull/98734/head:refs/nixpkgs-review/1
$ git worktree add /home/joerg/.cache/nixpkgs-review/pr-98734-1/nixpkgs 1d0cd06d37a34ff16b72ba15a8598dddf06c9a9e
Preparing worktree (detached HEAD 1d0cd06d37a)
Updating files: 100% (24774/24774), done.
HEAD is now at 1d0cd06d37a Merge pull request #82249 from caadar/gtklp
$ git merge --no-commit --no-ff 5587236f0f1b9eea35d762cf093c900affa3fe48
Auto-merging pkgs/top-level/python-packages.nix
Auto-merging pkgs/top-level/all-packages.nix
Auto-merging doc/languages-frameworks/python.section.md
Automatic merge went well; stopped before committing as requested
$ nix --experimental-features nix-command build --no-link --keep-going --option build-use-sandbox relaxed -f /home/joerg/.cache/nixpkgs-review/pr-98734-1/build.nix

Link to currently reviewing PR:
https://github.com/NixOS/nixpkgs/pull/98734

10 packages built:
python37Packages.beaker python37Packages.pyramid_beaker python37Packages.pyscss python38Packages.beaker python38Packages.pyramid_beaker python38Packages.pyscss python39Packages.beaker python39Packages.pyramid_beaker python39Packages.pyscss zerobin

$ git worktree prune
Traceback (most recent call last):
  File "/home/joerg/git/nixpkgs-review/bin/nix-review", line 14, in <module>
    main()
  File "/home/joerg/git/nixpkgs-review/nixpkgs_review/__init__.py", line 10, in main
    cli.main(command, args)
  File "/home/joerg/git/nixpkgs-review/nixpkgs_review/cli/__init__.py", line 262, in main
    return cast(str, args.func(args))
  File "/home/joerg/git/nixpkgs-review/nixpkgs_review/cli/pr.py", line 70, in pr_command
    review.start_review(attrs, path, pr, args.post_result)
  File "/home/joerg/git/nixpkgs-review/nixpkgs_review/review.py", line 249, in start_review
    nix_shell(report.built_packages(), path, self.run, self.system)
  File "/home/joerg/git/nixpkgs-review/nixpkgs_review/nix.py", line 46, in nix_shell
    write_shell_expression(shell, system, attrs)
  File "/home/joerg/git/nixpkgs-review/nixpkgs_review/nix.py", line 178, in write_shell_expression
    f.write(system)
TypeError: write() argument must be str, not None
~/git/nixpkgs-review/bin/nix-review pr --system=aarch64-linux 98734  5,52s user 4,59s system 78% cpu 12,844 total
```

2021-03-06 19:21 UTC, SuperSandro2000 commented on README.md
> +```console
console has not special highlighting.

2021-03-12 14:35 UTC, SuperSandro2000 commented
> This does not quite work yet:

The following now works correctly.

```
nix-build
(cd ../nixpkgs; ../nixpkgs-review/result/bin/nixpkgs-review pr --system=x86_64-linux 98734)
```

2021-03-12 14:43 UTC, SuperSandro2000 requested changes

2021-03-12 14:43 UTC, SuperSandro2000 commented on nixpkgs_review/nix.py
> +            """"; } }:
```suggestion
            """; } }:
```

2021-03-12 14:43 UTC, SuperSandro2000 commented on nixpkgs_review/nix.py
> +        f.write(system)
```suggestion
        f.write(f"{ pkgs ? import ./nixpkgs { system = \"{system}\"")
```

2021-03-12 15:33 UTC, SuperSandro2000 commented on README.md
> +```console
or it has. looks like it is bash.

2021-03-13 02:10 UTC, SuperSandro2000 commented
@Mic92 resolved and combined the commits.

2021-03-13 05:33 UTC, merged